### ISSUE TITLE
Sample apk crash

### ISSUE THREAD

**Issue by MohamedElidrissi** [TheAndroidMaster/RadialLayout#3]
The sample apk crashes after opening.
Device is Galaxy J7 Prime running Android Oreo.
Here is the log I was able to get :

FATAL EXCEPTION: main
Process: me.jfenn.radiallayoutsample, PID: 7687
java.lang.NullPointerException: Attempt to read from field 'float me.jfenn.radiallayout.BaseRadialItem.radius' on a null object reference
	at me.jfenn.radiallayout.RadialLayoutView.onTouchEvent(RadialLayoutView.java:323)
	at android.view.View.dispatchTouchEvent(View.java)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java)
	at android.app.Activity.dispatchTouchEvent(Activity.java)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java)
	at android.view.View.dispatchPointerEvent(View.java)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by TheAndroidMaster** [comment]
Why is this issue closed? Can you not reproduce it anymore? The log seems legitimate.

**Comment by MohamedElidrissi** [comment]
@TheAndroidMaster This happened in like the 5 first launches but now its gone, I have no idea why

**Comment by MohamedElidrissi** [comment]
@TheAndroidMaster I think I got it, its happening when the view is touched before its drawn

**Comment by TheAndroidMaster** [comment]
Yep, was just about to reopen this issue, I just found the line where it's going wrong in the source, it's not accounting for anything happening before the "center item" has been set.
